<h1>Hiragana Table</h1>
<p>
    Hiragana was developed from
    <em>kanji<meaning>chinese characters</meaning></em>,
    that were used for pronunciation only without considering their meaning.
    As fast-writing got common, these
    <em>kanji<meaning>chinese characters</meaning></em>
    got deformed and simplified.
</p>
<p>
    This writing system consists of 46 main characters and 25 voiced characters. Knowing the pronunciation of these
    gives you the skill to say <strong>everything</strong> possible in japanese.
</p>
<p>
    You can put a character from the i-column add a small version of the y-row together to get a doubled vocal
    syllable.
    This "fusion" removes the <strong>i</strong> (or <strong>iy</strong> on irregular) from the new one.<br>
    <jap>き<meaning>ki</meaning></jap> +
    <jap>ゃ<meaning>ya ( a bit smaller as the original )</meaning></jap> =
    <jap>きゃ<meaning>kya</meaning></jap><br>
    <jap>し<meaning>shi</meaning></jap> +
    <jap>ょ<meaning>yo ( a bit smaller as the original )</meaning></jap> =
    <jap>しょ<meaning>sho</meaning></jap><br>
    <jap>じ<meaning>ji</meaning></jap> +
    <jap>ょ<meaning>yo ( a bit smaller as the original )</meaning></jap> =
    <jap>じょ<meaning>jo</meaning></jap>
</p>
<p>
    Consonants can also be doubled. Therefore you put a small <strong>tsu</strong> and a consonantal character together.<br>
    <jap>だ<meaning>da</meaning></jap> +
    <jap>っ<meaning>tsu ( a bit smaller as the original )</meaning></jap> +
    <jap>た<meaning>ta</meaning></jap> =
    <jap>だった<meaning>datta</meaning></jap><br>
    <jap>と<meaning>to</meaning></jap> +
    <jap>っ<meaning>tsu ( a bit smaller as the original )</meaning></jap> +
    <jap>し<meaning>shi</meaning></jap> =
    <jap>とっし<meaning>tosshi</meaning></jap><br>
    <jap>ま<meaning>ma</meaning></jap> +
    <jap>っ<meaning>tsu ( a bit smaller as the original )</meaning></jap> +
    <jap>ち<meaning>chi</meaning></jap> =
    <jap>まっち<meaning>macchi</meaning></jap><br>
</p>
<table class="kana-table">
    <tr>
        <td colspan="2">あ<meaning>a</meaning></td>
        <td colspan="2">い<meaning>i</meaning></td>
        <td colspan="2">う<meaning>u</meaning></td>
        <td colspan="2">え<meaning>e</meaning></td>
        <td colspan="2">お<meaning>o</meaning></td>
    </tr>
    <tr>
        <td>か<meaning>ka</meaning></td>
        <td>が<meaning>ga</meaning></td>
        <td>き<meaning>ki</meaning></td>
        <td>ぎ<meaning>gi</meaning></td>
        <td>く<meaning>ku</meaning></td>
        <td>ぐ<meaning>gu</meaning></td>
        <td>け<meaning>ke</meaning></td>
        <td>げ<meaning>ge</meaning></td>
        <td>こ<meaning>ko</meaning></td>
        <td>ご<meaning>go</meaning></td>
    </tr>
    <tr>
        <td>さ<meaning>sa</meaning></td>
        <td>ざ<meaning>za</meaning></td>
        <td>し<meaning>shi ( not si )</meaning></td>
        <td>じ<meaning>ji ( not zi )</meaning></td>
        <td>す<meaning>su</meaning></td>
        <td>ず<meaning>zu</meaning></td>
        <td>せ<meaning>se</meaning></td>
        <td>ぜ<meaning>ze</meaning></td>
        <td>そ<meaning>so</meaning></td>
        <td>ぞ<meaning>zo</meaning></td>
    </tr>
    <tr>
        <td>た<meaning>ta</meaning></td>
        <td>だ<meaning>da</meaning></td>
        <td>ち<meaning>chi ( not ti )</meaning></td>
        <td>ぢ<meaning>ji ( not di, じ is the common one )</meaning></td>
        <td>つ<meaning>tsu ( not tu )</meaning></td>
        <td>づ<meaning>zu ( not du, ず is the common one )</meaning></td>
        <td>て<meaning>te</meaning></td>
        <td>で<meaning>de</meaning></td>
        <td>と<meaning>to</meaning></td>
        <td>ど<meaning>do</meaning></td>
    </tr>
    <tr>
        <td colspan="2">な<meaning>na</meaning></td>
        <td colspan="2">に<meaning>ni</meaning></td>
        <td colspan="2">ぬ<meaning>nu</meaning></td>
        <td colspan="2">ね<meaning>ne</meaning></td>
        <td colspan="2">の<meaning>no</meaning></td>
    </tr>
    <tr>
        <td colspan="2">は<meaning>ha ( wa, when used as particle )</meaning></td>
        <td colspan="2">ひ<meaning>hi</meaning></td>
        <td colspan="2">ふ<meaning>fu ( not hu )</meaning></td>
        <td colspan="2">へ<meaning>he ( e, when used as particle )</meaning></td>
        <td colspan="2">ほ<meaning>ho</meaning></td>
    </tr>
    <tr>
        <td>ば<meaning>ba</meaning></td>
        <td>ぱ<meaning>pa</meaning></td>
        <td>び<meaning>bi</meaning></td>
        <td>ぴ<meaning>pi</meaning></td>
        <td>ぶ<meaning>bu</meaning></td>
        <td>ぷ<meaning>pu</meaning></td>
        <td>べ<meaning>be</meaning></td>
        <td>ぺ<meaning>pe</meaning></td>
        <td>ぼ<meaning>bo</meaning></td>
        <td>ぽ<meaning>po</meaning></td>
    </tr>
    <tr>
        <td colspan="2">ま<meaning>ma</meaning></td>
        <td colspan="2">み<meaning>mi</meaning></td>
        <td colspan="2">む<meaning>mu</meaning></td>
        <td colspan="2">め<meaning>me</meaning></td>
        <td colspan="2">も<meaning>mo</meaning></td>
    </tr>
    <tr>
        <td colspan="2">や<meaning>ya</meaning></td>
        <td colspan="2">ー</td>
        <td colspan="2">ゆ<meaning>yu</meaning></td>
        <td colspan="2">ー</td>
        <td colspan="2">よ<meaning>yo</meaning></td>
    </tr>
    <tr>
        <td colspan="2">ら<meaning>ra</meaning></td>
        <td colspan="2">り<meaning>ri</meaning></td>
        <td colspan="2">る<meaning>ru</meaning></td>
        <td colspan="2">れ<meaning>re</meaning></td>
        <td colspan="2">ろ<meaning>ro</meaning></td>
    </tr>
    <tr>
        <td colspan="2">わ<meaning>wa</meaning></td>
        <td colspan="2">ー</td>
        <td colspan="2">ー</td>
        <td colspan="2">ー</td>
        <td colspan="2">を<meaning>wo ( o, when used as particle)</meaning></td>
    </tr>
    <tr>
        <td colspan="10">ん<meaning>n</meaning></td>
    </tr>
</table>
<table class="kana-table">
    <tr>
        <td>きゃ<meaning>kya</meaning></td>
        <td>きゅ<meaning>kyu</meaning></td>
        <td>きょ<meaning>kyo</meaning></td>
    </tr>
    <tr>
        <td>ぎゃ<meaning>gya</meaning></td>
        <td>ぎゅ<meaning>gyu</meaning></td>
        <td>ぎょ<meaning>gyo</meaning></td>
    </tr>
    <tr>
        <td>しゃ<meaning>sha ( not sya )</meaning></td>
        <td>しゅ<meaning>shu ( not syu )</meaning></td>
        <td>しょ<meaning>sho ( not syo )</meaning></td>
    </tr>
    <tr>
        <td>じゃ<meaning>ja ( not jya or zya )</meaning></td>
        <td>じゅ<meaning>ju ( not jyu or zyu )</meaning></td>
        <td>じょ<meaning>jo ( not jyo or zyo)</meaning></td>
    </tr>
    <tr>
        <td>ちゃ<meaning>cha ( not chya or tya )</meaning></td>
        <td>ちゅ<meaning>chu ( not chyu or tyu )</meaning></td>
        <td>ちょ<meaning>cho ( not chyo or tyo )</meaning></td>
    </tr>
    <tr>
        <td>ぢゃ<meaning>ja ( not jya or dya, じゃ is the common one )</meaning></td>
        <td>ぢゅ<meaning>ju ( not jyu or dyu, じゅ is the common one )</meaning></td>
        <td>ぢょ<meaning>jo ( not jyo or dyo, じょ is the common one )</meaning></td>
    </tr>
    <tr>
        <td>にゃ<meaning>nya</meaning></td>
        <td>にゅ<meaning>nyu</meaning></td>
        <td>にょ<meaning>nyo</meaning></td>
    </tr>
    <tr>
        <td>ひゃ<meaning>hya</meaning></td>
        <td>ひゅ<meaning>hyu</meaning></td>
        <td>ひょ<meaning>hyo</meaning></td>
    </tr>
    <tr>
        <td>びゃ<meaning>bya</meaning></td>
        <td>びゅ<meaning>byu</meaning></td>
        <td>びょ<meaning>byo</meaning></td>
    </tr>
    <tr>
        <td>ぴゃ<meaning>pya</meaning></td>
        <td>ぴゅ<meaning>pyu</meaning></td>
        <td>ぴょ<meaning>pyo</meaning></td>
    </tr>
    <tr>
        <td>みゃ<meaning>mya</meaning></td>
        <td>みゅ<meaning>myu</meaning></td>
        <td>みょ<meaning>myo</meaning></td>
    </tr>
    <tr>
        <td>りゃ<meaning>rya</meaning></td>
        <td>りゅ<meaning>ryu</meaning></td>
        <td>りょ<meaning>ryo</meaning></td>
    </tr>
</table>