<?= lessonHeader('Particle ' . roma('o')); ?>
<p>
    We had our first particle in <a href="/Lessons/2">Lesson 2</a>. Our next particle is
    <?= jap('を', 'object marker particle', true); ?>, the object marker. Note that
    <?= jap('を', 'object marker particle', true); ?> is written with the mora
    <?= roma('wo'); ?>, but with its function as a particle, it has to be read as <?= roma('o'); ?>.
    There aren't words which contain
    <?= jap('を', 'object marker particle', true); ?>, so it's just used as a particle and you never have
    to pronounce <?= roma('wo'); ?> (except if you're into J-Pop).
</p>
<p>
    A noun followed by <?= jap('を', 'object marker particle', true); ?>
    is marked as something that is used somehow (accusative).<br>
    <?= jap('じてんしゃ', 'bicycle'); ?>
    <?= jap('を', 'object marker particle', true); ?>
    [verb] ➤ [verb] the/a bike (e.g. buy a bike)<br>
    <?= jap('まり', 'a girl\'s name'); ?>
    <?= jap('を', 'object marker particle', true); ?>
    <?= jap('みつける', 'to find'); ?>
    ➤ find Mari<br>
    <?= jap('みち', 'road'); ?>
    <?= jap('を', 'object marker particle', true); ?>
    <?= jap('あるく', 'to walk'); ?>
    ➤ walk (on) the road
</p>
<p>
    Note: Unfortunately, from a grammatical point of view, a <strong>road</strong> isn't a location but an object you
    can use (for walking on).
</p>

