<?= lessonHeader('Sentence Construction'); ?>
<p>
    Sentences can get complicated in every language and Japanese isn't an exception. The basics are simple though. In
    English, you have the S-V-O (subject, object, verb) and in Japanese it's <strong>S-O-V</strong>. As mentioned before
    the predicate is always at the end. The subject and object can be omitted when clear, but never the predicate.
    Remember that a particle always sticks to the preceding word, you can take the word and its particle as a solid
    block. The block though can be switched in most cases.
</p>
<p>
    To understand a sentence you should first considering its theme and omitted subjects/objects and then
    <strong>begin with the predicate</strong> and move <strong>blockwise from right to left</strong>, or else you will
    misunderstand its meaning.
</p>
<p>
    Sentence examples:
</p>
<ul>
    <li>
        <p>
            <?= jap('ほん', 'book'); ?>
            <?= jap('を', 'object marker particle', true); ?>
            <?= jap('よむ', 'to read'); ?>
            ➤ read a book<br>
            Starting with <?= jap('よむ', 'to read'); ?>, you know that the main statement is "read".
            <?= jap('ほん', 'book'); ?>
            <?= jap('を', 'object marker particle', true); ?>
            stick together (see <a href="/Lessons/1">Lesson 1</a>) and indicate that something will be done
            to the book, namely the predicate <?= jap('よむ', 'to read'); ?>.
        </p>
    </li>
    <li>
        <p>
            <?= jap('こども', 'child'); ?>
            <?= jap('の', 'possession particle'); ?>
            <?= jap('おもちゃ', 'toy'); ?>
            <?= jap('を', 'object marker particle', true); ?>
            <?= jap('とる', 'to take'); ?>
            ➤ take child's toy / take a toy from a child<br>
            Separate the blocks from right to left, i.e. <?= jap('とる', 'to take'); ?>,
            <?= jap('おもちゃ', 'toy'); ?>
            <?= jap('を', 'object marker particle', true); ?>,
            and <?= jap('こども', 'child'); ?> <?= jap('の', 'possession particle'); ?>.
            Bind the blocks by asking for the next step: Take... Take what? A toy... Whom toy? Child's...
        </p>
    </li>
</ul>
<p>
    Don't hurry to translate by just seeing the sentence. If you aren't experienced, it's easier to translate it
    as "a child takes a toy" - which is wrong. I'm telling you this because of my personal failures.
</p>
