<?= lessonHeader('Tenses'); ?>
<p>
    It's good to heat that there are only two tenses in Japanese, <strong>past and non-past</strong>. A non-specified
    sentence has to be understood as not yet applied plans, such as our examples in previous lessons. That fact
    doesn't mean that other tenses can't be expressed, but that you haven't to learn new forms or concepts.
</p>
<p>
    Here's an example (ignore unknown grammar):<br>
    <?= jap('まり', 'a girl\'s name'); ?>
    <?= jap('が', 'subject marker particle'); ?>
    <?= jap('えいが', 'film; movie'); ?>
    <?= jap('を', 'object marker particle', true); ?>
    <?= jap('みる', 'to see; to watch'); ?>
    ➤ Mari watches a film.<br>
</p>
<p>
    It isn't specified, when she does it. It is a sure thing, that she <strong>hadn't</strong> done it and that she
    <strong>isn't</strong> doing it right now. We just know that she intends to do it sometime, maybe soon, maybe in her
    next life, or maybe it's just a habit of her.
</p>
