<?= lessonHeader('Verb Agglutination'); ?>
<p>
    In English, you use words as prepositions to bring sense in.<br>
    - You <strong>do not</strong> eat mushrooms.<br>
    - We <strong>want to</strong> eat mushrooms<br>
    - She <strong>should</strong> eat mushrooms.<br>
    In Japanese, such prepositions don't exist. They use affixes or sub-forms on the verb. However these affixes can't
    be simply added to the verb, because the verb form and the sub-form have to be made "compatible" first
    (see <a href="/Lessons/7">Lesson 7</a>).
</p>
<p>
    Maybe you remember Dominoes, that old tile-based game from your childhood. Even if you don't know them, you will
    understand the concept very easily. In our analogy tough let's assume, blank sides are unchangeable and can't
    combine with other blank ones.<br>
</p>
<p>
    A verb contains a stem and an ending. Something like this: <span class="domino">🀵</span><br>
    Affixes/sub-forms can be double-sided <span class="domino">🀻</span> or have a non-transformable ending
    <span class="domino">🁔</span><br>
    You surely had figured out that <span class="domino">🀵</span> and <span class="domino">🀻</span> don't fit.<br>
    What you can do is to transform the verb's ending from <span class="domino">🀵</span> to
    <span class="domino">🀲</span><br>
    Now you have <span class="domino">🀲🀻</span> and need to change the ending from the sub-form to
    <span class="domino">🀽</span><br>
    And you get <span class="domino">🀲🀽🁔</span>
</p>
<p>
    The last tile doesn't have to be an unchangeable one because (in some cases) all tiles can terminate. They also can
    be as long as possible until they met an unchangeable tile.<br>
    <span class="domino">🀲🀽🁖🁃🁓</span> and <span class="domino">🀲🀽🁖🁃🁍</span> are possible.
</p>

