<?= lessonHeader(roma('Ren\'yōkei')); ?>
<p>
    It's hard to describe, what a form stands for because there's no clear or too complex definition for any of them. In
    further lessons you will understand, how to use the
    <roma>Ren'yōkei</roma>
    (RYK) - The Continuative Form. For now, just
    remember how to build it.
</p>
<p>
    Remember our verb groups from <a href="/Lessons/6">Lesson 6</a>? Build them like following:
</p>
<ul>
    <li>
        <p>
            The RYK for <?= jap('する', 'to do; to make'); ?> is <?= jap('し'); ?>
        </p>
    </li>
    <li>
        <p>
            The RYK for <?= jap('くる', 'to come'); ?> is <?= jap('き'); ?>
        </p>
    </li>
    <li>
        <p>
            The RYK for lvl1 is quite simple, just the stem.<br>
            Example: <?= jap('たべる', 'to eat'); ?> ➤ <?= jap('たべ'); ?>
        </p>
    </li>
    <li>
        <p>
            The RYK for lvl5 is a little more complicated. The ending has to be replaced by its neighbour from the
            i-column.<br>
            Example: <?= jap('とぶ', 'to jump; to fly'); ?> ➤ <?= jap('とび'); ?>
        </p>
    </li>
</ul>
<p>
    "I got it, for lvl5 I just have to switch u and i."<br>
    Uhm... no. The ending is
    <roma>bu</roma>
    , so you replace it by
    <roma>bi</roma>
    .<br>
    "You're just splitting hairs!"<br>
    Maybe... but there's a reason. If I would follow this rule,
    <?= roma('korosu', 'to kill; to murder'); ?> would become
    <roma>korosi</roma>
    , but there's no "si" in Japanese
    language. The neighbour of
    <roma>su</roma>
    in the i-column is
    <roma>shi</roma>
    , so it's
    <roma>koroshi</roma>
    .
</p>


