<?= lessonHeader(roma('masu').'-form'); ?>
<p>
    Japanese has a very complicated politeness-system with several levels, relationships and other formalities. The
    <roma>masu</roma>-form is the common one, which is used in everyday conversation. I'm afraid you can't translate it into
    English, but not to use it makes you a rude or vulgar person, so use it while you speak to a person you respect.
</p>
<p>
    The <roma>masu</roma>-form is appended to a verb in the RYK, exactly the predicate, other verbs in a sentence must not
    be in this form. Formula: verb[RYK] + <roma>masu</roma>
</p>
<table>
    <tr>
        <th>Verb Group</th>
        <th>SSK</th>
        <th>RYK</th>
        <th><roma>masu</roma></th>
        <th>Meaning</th>
    </tr>
    <tr>
        <td>suru</td>
        <td><roma>suru</roma></td>
        <td><roma>shi</roma></td>
        <td><roma>shimasu</roma></td>
        <td>to do</td>
    </tr>
    <tr>
        <td>kuru</td>
        <td><roma>kuru</roma></td>
        <td><roma>ki</roma></td>
        <td><roma>kimasu</roma></td>
        <td>to come</td>
    </tr>
    <tr>
        <td>lvl1</td>
        <td><roma>yameru</roma></td>
        <td><roma>yame</roma></td>
        <td><roma>yamemasu</roma></td>
        <td>to stop</td>
    </tr>
    <tr>
        <td>lvl5</td>
        <td><roma>matsu</roma></td>
        <td><roma>machi</roma></td>
        <td><roma>machimasu</roma></td>
        <td>to wait</td>
    </tr>
</table>
<p>
    This form is not about <strong>what</strong> you tell, but <strong>to whom</strong> you speak. Even if you speak
    about crap, you should be polite if you speak to a professor. If you have problems remembering the RYK, please use
    the <a href="/Training/VerbForms">verb form trainer</a> provided by this page.
</p>
