<?= lessonHeader('Subject Marking Particle'); ?>
<p>
    Let me introduce the particle <roma>ga</roma>. It has many functions, but now we will cover its function as the
    <strong>subject marker</strong>. By subject is meant the actor who is going to perform the decisive action
    (predicate).
</p>
<p>
    Example:
    <?= jap('とりやまさん', 'Mr. Toriyama'); ?>
    <?= jap('の', 'possession particle'); ?>
    <?= jap('むすこ', 'son'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('アニメ', 'You weren\'t here if you don\'t know what that is!'); ?>
    <?= jap('を', 'object marker particle', true); ?>
    <?= jap('みます。', 'to see; to watch'); ?><br>

    <?= jap('みます', 'to see; to watch'); ?> :
    <?= jap('みる', 'to see; to watch'); ?> +
    <?= jap('ます', 'common politeness form'); ?> watch (watch what?)<br>
    <?= jap('アニメ', 'It\'s what you think'); ?>
    <?= jap('を', 'object particle', true); ?> : an anime (who watches an anime?)<br>
    <?= jap('むすこ', 'son'); ?>
    <?= jap('が', 'subject marker particle'); ?> : the son (whom son watches an anime?)<br>
    <?= jap('とりやまさん', 'Mr. Toriyama'); ?>
    <?= jap('の', 'possession particle'); ?> : Toriyama-san's<br>
    ➤ Toriyama-san's son is going to watch an anime.<br>
</p>
