<?= lessonHeader('Copula'); ?>
<p>
    If you're followed the lessons so far, you must've been missing the copula. Don't let confuse you by this special
    term as it's very familiar to you. It's a verb that means <strong>be</strong> (or is, am, are). In Japanese:
    <?= jap('である', 'to be'); ?>. It's mainly used as the predicate and you shouldn't use it in-between,
    until it's an attribute.
</p>
<p>
    What if we want to be polite in a sentence where the copula is the predicate? Since it's a verb, we can simply use
    the <roma>masu</roma>-form on it. First, we need the RYK, that is <?= jap('であり'); ?> and then add
    <?= jap('ます', 'common politeness form'); ?> which lead us to
    <?= jap('であります', 'to be'); ?>. Because of laziness and the fact that this is an unnecessary long term,
    a more comfortable version has arisen. The centre was cut so that just the first and the last mora remained. I'm
    certain, you heard <?= jap('です', 'to be'); ?> zillion times. Never use the long one, it's not
    extraordinary, it's just wrong.
</p>
<p>
    There's also a rude/manly version <?= jap('だ', 'to be'); ?> which originally has its use in the grammar.
</p>
<p>
    Examples:<br>

    <?= jap('わたし', 'I'); ?>
    <?= jap('が', 'subject marker particle'); ?>
    <?= jap('がくせい', 'university student'); ?>
    <?= jap('です', 'to be'); ?> ➤ I'm a university student.<br>

    <?= jap('です', 'to be'); ?> : be (be what?)<br>
    <?= jap('がくせい', 'university student'); ?> : university student (who is a student?)<br>
    <?= jap('わたし', 'I'); ?>
    <?= jap('が', 'subject marker particle'); ?> : I (am performing the main action, namely, to be a student)
</p>
<p>
    <?= jap('にほん', 'Japan'); ?>
    <?= jap('が', 'subject marker particle'); ?>
    <?= jap('ひがし', 'east'); ?>
    <?= jap('の', 'possession particle'); ?>
    <?= jap('くに', 'country'); ?>
    <?= jap('である', 'to be'); ?> ➤ Japan is an eastern country.<br>

    <?= jap('である', 'to be'); ?> : be (be what?)<br>
    <?= jap('くに', 'country'); ?> : country (what country?)<br>
    <?= jap('ひがし', 'east'); ?>
    <?= jap('の', 'possession particle'); ?> : eastern (which country is an eastern one?)<br>
    <?= jap('にほん', 'Japan'); ?>
    <?= jap('が', 'subject marker particle'); ?> : Japan (the main actor)
</p>
<p>
    <?= jap('こばやし', 'last name'); ?>
    <?= jap('たろう', 'first name'); ?>
    <?= jap('だ', 'to be'); ?> ➤ He's Tarō Kobayashi.<br>
</p>
<p>
    In the last sentence, the actor isn't specified, but it doesn't mean there is no. The actor was omitted because
    he is perfectly clear to both the speaker and the listener(s). Hence, a translation like "Someone is Tarō
    Kobayashi" would be wrong since it's been spoken about a particular individual. Without the question, that preceded
    this statement you can't translate it correctly, or rather, all translation that involves a particular subject are
    correct, i.e. "You are ...", "She is ..." and "I am ..." could be just as legitimate as "He is ...".
</p>
