<?= lessonHeader('Masu & Copula'); ?>
<p>
    We didn't discuss these themes in detail, but there's really not much to explain. We will review it plenty enough
    anyway. I recommend to remember the following tables:
</p>
<p>
    With the <roma>masu</roma>-form, you can use the denial-form and past-tense very easily without knowing how it works on
    regular forms. Replace <roma>masu</roma> by <roma>masen</roma> to express a denying statement (do not) and <roma>mashita</roma>
    to move an action in the past (did). You can also deny an action in the past with <roma>masen deshita</roma> (did not).
    Of course we will cover denials and past tenses in further lessons.
</p>
<table>
    <tr>
        <th></th>
        <th>Affirmative</th>
        <th>Negative</th>
        <th>Past</th>
        <th>Negative Past</th>
    </tr>
    <tr>
        <th><roma>matsu</roma> + <roma>masu</roma></th>
        <td><roma>machimasu</roma></td>
        <td><roma>machimasen</roma></td>
        <td><roma>machimashita</roma></td>
        <td><roma>machimasen deshita</roma></td>
    </tr>
    <tr>
        <th>Meaning</th>
        <td>wait</td>
        <td>do not wait</td>
        <td>did wait</td>
        <td>did not wait</td>
    </tr>
</table>
<p>
    For <roma>dearu</roma> it's relatively easy, too. It seems like much, but it isn't if you consider that the list is
    complete.
</p>
<table>
    <tr>
        <th></th>
        <th>Affirmative</th>
        <th>Negative</th>
        <th>Past</th>
        <th>Negative Past</th>
    </tr>
    <tr>
        <th>copula objective/neutral</th>
        <td><roma>dearu</roma></td>
        <td><roma>dewa nai</roma><br><roma>ja nai</roma></td>
        <td><roma>datta</roma></td>
        <td><roma>dewa nakatta</roma><br><roma>ja nakatta</roma></td>
    </tr>
    <tr>
        <th>copula rude</th>
        <td><roma>da</roma></td>
        <td><roma>ja nai</roma></td>
        <td><roma>datta</roma></td>
        <td><roma>ja nakatta</roma></td>
    </tr>
    <tr>
        <th>copula polite</th>
        <td><roma>desu</roma></td>
        <td><roma>dewa arimasen</roma><br><roma>ja arimasen</roma></td>
        <td><roma>deshita</roma></td>
        <td><roma>dewa arimasen deshita</roma><br><roma>ja arimasen deshita</roma></td>
    </tr>
    <tr>
        <th>Meaning</th>
        <td>be/is/am/are</td>
        <td>be/is/am/are not</td>
        <td>was/were</td>
        <td>was/were not</td>
    </tr>
</table>
<p>
    Instead of <roma>dewa/ja arimasen</roma>, <roma>dewa/ja nai desu</roma> is possible but is less cool. The same for the
    past ones. Some argue <roma>dewa</roma> is more polite than <roma>ja</roma>, however, there's no clear result from this
    discussion.
</p>