<?= $global->lessonHeader('Particle ' . $global->roma('no', 'possession particle')); ?>
<p>
    The first particle we will learn is <?= $global->jap('の', 'possession particle'); ?> with its possessive meaning.
    If there's a noun followed by <?= $global->jap('の', 'possession particle'); ?>,
    this noun is understood as the owner of something. This "something" can be an object or an attribute.
</p>
<p>
    <?= $global->jap('まり', 'a girl\'s name'); ?>
    <?= $global->jap('の', 'possession particle'); ?>
    ➤ Mari's (Something belongs to Mari)<br>

    <?= $global->jap('まり', 'a girl\'s name'); ?>
    <?= $global->jap('の', 'possession particle'); ?>
    <?= $global->jap('こども', 'child'); ?>
    ➤ Mari's child / Child of Mari (It doesn't mean Mari owns the child)<br>

    <?= $global->jap('まり', 'a girl\'s name'); ?>
    <?= $global->jap('の', 'possession particle'); ?>
    <?= $global->jap('こども', 'child'); ?>
    <?= $global->jap('の', 'possession particle'); ?>
    <?= $global->jap('おもちゃ', 'toy'); ?>
    ➤ Mari's child's toy / Toy of Mari's child / Toy of child of Mari
</p>
<p>
    Sure you can see, it can be specified and stacked very easily.
</p>