<?= lessonHeader('Adjectives'); ?>
<p>
    In this lesson we're going to explore adjectives or rather "i-adjectives". That naming refers to their appearance,
    namely the obligatory <?= jap('い'); ?> on the end.<br>
    Check this out:
    <?= jap('はやい', 'to be fast'); ?>,
    <?= jap('ねむい', 'to be sleepy'); ?>,
    <?= jap('つまらない', 'to be boring'); ?>.
</p>
<p>
    Did you notice the "to be" in their translation. That's exactly what's confusing about adjectives.
    They're implicating the <a href="/Lessons/18">copula</a>, which can't be removed nor added. That means that
    <?= jap('はやい', 'to be fast'); ?> must not be translated as "fast", nor is
    <?= jap('はやい', 'to be fast'); ?> <?= jap('である', 'to be'); ?> allowed.<br>
    Don't worry, it gets more complicated.
</p>
<p>
    The main question is whether it is really an adjective, because "to be" implicates an action, so it actually has to
    be a verb - but it isn't. The solution is not to compare them to adjectives how you know them - because
    they aren't. In the beginning it's ok to treat them like "normal" adjectives, but as we progress, you should be
    aware of many nuances which often make a difference.
</p>
<p>
    The main forms for i-adjectives are pretty easy, too. The <?= roma('Shūshikei', 'Terminal Form'); ?>
    is the same as above, of course. For the <?= roma('Ren\'yōkei'); ?> it's a <?= jap('く'); ?> replacing the
    ending <?= jap('い'); ?>.<br> <?= jap('はやい', 'to be fast'); ?> becomes <?= jap('はやく'); ?>
</p>
