<?= lessonHeader('Adjectives polite'); ?>
<p>
    Check this out: <?= jap('みず', 'water'); ?> <?= jap('が', 'subject particle'); ?>
    <?= jap('つめたい', 'to be cold (touchables)'); ?>. (The water is cold.)<br>
    What if we wanted to say that in a polite way? From the last section we know that we can use the
    <?= roma('masu'); ?>-form which has to be attached to the RYK. The problem is that <?= jap('つめたくます'); ?>
    <strong>don't</strong> work, the <?= roma('masu'); ?>-form can only be attached to <strong>verbs</strong>.
</p>
<p>
    What we can do is to add the copula with its <?= roma('masu'); ?>-form, which leads us to
    <?= jap('つめたい', 'to be cold (touchables)'); ?> <?= jap('です', 'to be (polite)'); ?>.
    You may complain here, because in the last lesson it has been said that this isn't allowed because of the double
    "to be". However, the copula here just serves the purpose of politeness and loses its word meaning. This compromise
    has to be made, because it's the only way to accomplish that.
</p>