<?= lessonHeader(roma('nai') . '-form'); ?>
<p>
    The <roma>nai</roma>-form does exactly what it sounds like - negating statements. It can be attached to MZK of both,
    verbs and i-adjectives. The following table illustrates the application.
</p>
<table>
    <tr>
        <th>Verb Group</th>
        <th>SSK</th>
        <th>MZK</th>
        <th><roma>nai</roma></th>
        <th>Meaning</th>
    </tr>
    <tr>
        <td>suru</td>
        <td><roma>suru</roma></td>
        <td><roma>shi</roma></td>
        <td><roma>shinai</roma></td>
        <td>not to do</td>
    </tr>
    <tr>
        <td>kuru</td>
        <td><roma>kuru</roma></td>
        <td><roma>ko</roma></td>
        <td><roma>konai</roma></td>
        <td>not to come</td>
    </tr>
    <tr>
        <td>lvl1</td>
        <td><roma>hajimeru</roma></td>
        <td><roma>hajime</roma></td>
        <td><roma>hajimenai</roma></td>
        <td>not to begin</td>
    </tr>
    <tr>
        <td>lvl5</td>
        <td><roma>wakaru</roma></td>
        <td><roma>wakara</roma></td>
        <td><roma>wakaranai</roma></td>
        <td>not to understand</td>
    </tr>
    <tr>
        <td>lvl5</td>
        <td><roma>tsukau</roma></td>
        <td><roma>tsukawa</roma></td>
        <td><roma>tsukawanai</roma></td>
        <td>not to use</td>
    </tr>
    <tr>
        <td>i-adj</td>
        <td><roma>takai</roma></td>
        <td><roma>takaku</roma></td>
        <td><roma>takakunai</roma></td>
        <td>not to be high/expensive</td>
    </tr>
</table>
<p>
    The building of the <roma>nai</roma>-form is pretty easy, but it results in something complicated that we should
    discussed further. The clue about <roma>nai</roma> is that it's actually an i-adjective. So if we attach
    <roma>nai</roma> to a verb, it fuses to a new word due to <a href="/Lessons/7">agglutination</a>. The consequence is
    that the new word obtains adjective-like behaviour and can no longer be treated like a verb.
</p>

