<?= lessonHeader('Theme Marking Particle'); ?>
<p>
    Here it comes, the particle you so long waited for: <?= jap('は', 'theme particle', true); ?>.<br>
    It may seem very familiar, common, and intuitive (at least for some
    <?= roma('otaku', 'HERE: fans of japanese popular culture'); ?>) but it's one of the most complex
    concepts. It's very important that its bad use doesn't become a habit of you in the first place, so try to keep up.
</p>
<p>
    The thing is that <?= jap('は', 'theme particle', true); ?> <strong>doesn't</strong> mark
    the subject like <?= jap('が', 'subject particle'); ?> do. It introduces the theme which from this
    point is known to both conversation partners and it hasn't to be used until the theme is changing. As mentioned in
    <a href="/Lessons/18">lesson 18</a> the subject can be omitted if known.
</p>
<p>
    Examples:<br>

    <?= jap('わたし', 'I'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('がくせい', 'university student'); ?>
    <?= jap('です', 'to be'); ?> ➤ I'm a university student.<br>

    <?= jap('わたし', 'I'); ?>
    <?= jap('は', 'theme particle', true); ?>
    <?= jap('がくせい', 'university student'); ?>
    <?= jap('です', 'to be'); ?> ➤ As for me, I'm a university student.<br>

    The difference here is the implication of the question that you wish to answer. If the question was like "What is
    <strong>your</strong> job?", the first answer would be appropriate. In the case if someone asks you to tell
    something about you, you could start with the second one. For a neutral statement which doesn't answer anything,
    <?= jap('がくせい', 'university student'); ?> <?= jap('です', 'to be'); ?> would be fine.
</p>
<p>
    The difference will get really clear with the following example. Imagine you're in a japanese restaurant and the
    waiter is asking for your order:<br>

    <?= jap('わたし', 'I'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('やきざかな', 'grilled fish'); ?>
    <?= jap('です', 'to be'); ?> ➤ I'm a grilled fish.<br>

    <?= jap('わたし', 'I'); ?>
    <?= jap('は', 'theme particle', true); ?>
    <?= jap('やきざかな', 'grilled fish'); ?>
    <?= jap('です', 'to be'); ?> ➤ As for me, It's (I'll take) grilled fish.<br>

    The first sentence does not make much sense, so be aware.
</p>
<p>
    Another nuance of <?= jap('は', 'theme particle', true); ?> is that it excludes other cases of
    the same type. If you make a statement about "A" using <?= jap('は', 'theme particle', true); ?>,
    it automatically implies that this statement doesn't apply to "B" and "C".<br>

    <?= jap('キム', 'I'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('うつくしくない', 'grilled fish'); ?> ➤ Kim isn't beautiful.<br>

    <?= jap('キム', 'I'); ?>
    <?= jap('は', 'theme particle', true); ?>
    <?= jap('うつくしくない', 'grilled fish'); ?> ➤ As for Kim, in contrast to other celebrities, she isn't beautiful.<br>
</p>
