<?= lessonHeader('Direction Marking Particle'); ?>
<p>
    There are two particles marking a direction or rather, destination. Basically with
    <?= jap('に', 'destination particle');?> you mark the destination and with
    <?= jap('へ', 'direction particle', true);?> the direction. It hardly makes difference if
    yo go <strong>somewhere</strong> or <strong>towards somewhere</strong>, so these particles are mostly interchangeable.
    <?= jap('へ', 'direction particle', true);?> is pronounced <roma>e</roma> instead of
    <roma>he</roma> if used as a particle.
</p>
<p>
    Examples:<br>
    <?= jap('きょう', 'today'); ?>
    <?= jap('えいがかん', 'cinema'); ?>
    <?= jap('に', 'destination particle'); ?>
    <?= jap('いきます', 'to go (polite)'); ?>　➤ Today I go to the cinema.<br>
    Here, <?= jap('へ', 'direction particle', true);?> would be also right.
</p>
<p>
    <?= jap('きのう', 'yesterday'); ?>
    <?= jap('きた', 'north'); ?>
    <?= jap('へ', 'direction particle', true);?>
    <?= jap('いきました', 'to go (polite, past)'); ?>　➤ Yesterday he went towards north.<br>
    In this case, <?= jap('に', 'destination particle'); ?> can't be used, because "north" isn't a
    specific destination.
</p>
