<?= lessonHeader('Movement'); ?>
<p>
    This lesson covers the main direction movement expressions <?= jap('行く', 'to go'); ?>,
    <?= jap('来る', 'to come'); ?>, and <?= jap('帰る', 'to return home'); ?>.
    These words seem self-explanatory, but there're some confusing nuances you should know. First of all, none of them
    imply physical transportation of someone's body, i.e. placing feet in an order that makes you travel in space-time
    (walking). They all indicate directions/destinations depending on the subject's location.
</p>
<ul>
    <li>
        <p>
            <?= jap('行く', 'to go'); ?>: You can go somewhere, but no one can go to you, because he would
            come instead.
        </p>
    </li>
    <li>
        <p>
            <?= jap('来る', 'to come'); ?>: Someone can come to you, but you can't come to no one, because
            <strong>coming</strong> referencing to the location you are already in.
        </p>
    </li>
    <li>
        <p>
            <?= jap('帰る', 'to return home'); ?>: You can return home, but you can't return somewhere you
            don't live, regardless if it was the last location visited. For this case you can use
            <?= jap('もどる', 'to return (location)'); ?> instead.
        </p>
    </li>
</ul>
<p>
    Examples:<br>
    <?= jap('あさって', 'the day after tomorrow'); ?>
    <?= jap('おばあさん', 'grandma'); ?>
    <?= jap('へ', 'direction particle', true); ?>
    <?= jap('いきます', 'to go (polite)'); ?>　➤ I go to my grandma in two days.<br>

    <?= jap('かぞく', 'family'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('びょういん', 'hospital'); ?>
    <?= jap('に', 'destination particle'); ?>
    <?= jap('きました', 'to come (polite, past)'); ?>　➤ My family came (for me) to the hospital.<br>

    <?= jap('かのじょ', 'she'); ?>
    <?= jap('は', 'topic particle', true); ?>
    <?= jap('かえらない', 'to return home (negative)'); ?>　➤ She ain't go home.<br>
</p>