<?= lessonHeader(roma('tai').'-form'); ?>
<p>
    The <roma>tai</roma>-form serves the purpose of expressing one's own will to perform an action. It is
    attached to the RYK of verbs and like the <a href="/Lessons/24"><roma>nai</roma>-form</a> it gives the new created
    word adjective-like behaviour.
</p>
<p>
    Pay attention to not use it for other people, because the japanese never do. In Japan it's unwelcome to make
    statements about other people. Even adjectives that express feelings are hardly used for others. Especially you can't
    read others' minds and can impossibly know what others want - guessing isn't very polite. So if the <roma>tai</roma>-form
    is used without a subject, it is perfectly clear that it refers to yourself.
</p>
<p>
    <?= jap('ともだち', 'friend'); ?>
    <?= jap('に', 'destination particle'); ?>
    <?= jap('おもちゃ', 'toy'); ?>
    <?= jap('を', 'object particle', true); ?>
    <?= jap('かえしたくない', 'to return (object) (willing, negative)'); ?>　
    ➤ I don't want to return the toy to my friend.<br>

    <?= jap('いつか', 'sometime'); ?>
    <?= jap('スターウォーズ', 'what do you guess?'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('みたい', 'to see/watch (willing)'); ?>
    <?= jap('です', 'HERE: politeness appendix'); ?>
    ➤ Sometime I want to watch STAR WARS.<br>
</p>
<p>
    As verbs are used to be marked by <?= jap('を', 'object particle', true); ?>, and adjectives
    by <?= jap('が', 'subject particle'); ?>, both <?= jap('を', 'object particle', true); ?> and
    <?= jap('が', 'subject particle'); ?> are possible. <?= jap('を', 'object particle', true); ?>
    may be more intuitive since it intend an action, however <?= jap('が', 'subject particle'); ?> is
    encouraged because the word form is technically an adjective.
</p>
