<?= lessonHeader('Spelling'); ?>
<p>
    Original Japanese isn't written with roman letters, but with
    <?= roma('Kana', 'the japanese writing systems Hiragana and Katakana'); ?>
    and
    <?= roma('Kanji', 'fancy hieroglyph-like pictures'); ?>.
    Anything you can say in Japanese you can write in
    <?= roma('Kana', 'the japanese writing systems Hiragana and Katakana'); ?>,
    hence
    <?= roma('Kanji', 'fancy hieroglyph-like pictures'); ?>
    can be written in
    <?= roma('Kana', 'the japanese writing systems Hiragana and Katakana'); ?>
    too.
    <?= roma('Kana', 'the japanese writing systems Hiragana and Katakana'); ?>
    consists of syllables, which pronunciation length is equal - called <strong>mora</strong>.
    Even though you don't know
    <?= roma('Kana', 'the japanese writing systems Hiragana and Katakana'); ?>,
    you should think of syllables, instead of letters.
</p>
<p>
    So if you are spelling Japanese, you shouldn't spell it letter-wise, but mora-wise.
    The word
    <?= jap('はなび', 'fireworks'); ?>
    is spelt "ha na bi", instead of "h a n a b i" and
    <?= jap('ちんたつげきとう', 'just a fictional word'); ?>
    is spelt "chi n ta tsu ge ki to u".
    If you're asked, what the ending of
    <?= jap('まねく', 'to invite'); ?>
    is, then it's not "u", but "ku".
</p>
<p>
    Please note that all mora's pronunciation lengths are equal. For instance, <?= roma('n'); ?> is stressed
    like "nnh" and double consonants or double vocals have its combination written out. Still don't get it? See this
    <a href="<?= '/Collection/HiraganaTable'; ?>"><?= roma('Hiragana', 'a japanese writing system'); ?>
        table</a>. Each character is exactly one mora.
</p>