<?= lessonHeader('Locating'); ?>
<p>
    In this lesson we'll learn how to locate things like "there are" or "here is". Therefore there are two verbs
    with the same meaning but different references, which aren't reasonable to westerners and other normal people.
</p>
<ul>
    <li>
        <p>
            First there's <?= jap('いる', 'to exist'); ?> that locate all conscious beings like humanoids,
            animals and other fictional species.
        </p>
    </li>
    <li>
        <p>
            However, the most used one is <?= jap('ある', 'to exist'); ?> because it covers all the other
            things that are either dead or abstract. Plants are also represented here, even though they're alive.
        </p>
    </li>
</ul>
<p>
    The location of existence is marked by <?= jap('に', 'existence particle'); ?>. That's the first time
    we meet a well known particle with a secondary function. I recommend you to treat it as a completely different
    particle that coincidentally shares the same character (pronounciation). Unfortunately, it's not alone out there -
    several particles have multiple functions. But don't be afraid, the context will specify the solution.
</p>
<p>
    <?= jap('いる', 'to exist'); ?> is a regular lvl1 verb, while <?= jap('ある', 'to exist'); ?>
    is regular lvl5. However, there's one thing that makes <?= jap('ある', 'to exist'); ?> behave strange.
    The negation of <?= jap('ある', 'to exist'); ?> would expect <?= jap('あらない'); ?>, according to
    the negation rule (MZK + <roma>nai</roma>). Instead, the adjective <?= jap('ない', 'to be not existent'); ?>
    is used. This don't apply to the <roma>masu</roma>-form and it's still <?= jap('ありません', 'to be not existent (polite)'); ?>.
    Actually, the <roma>nai</roma>-form derived from that adjective - so instead of
    <?= jap('したくない', 'not want to do'); ?> <?= jap('です', 'HERE: politeness marker'); ?>
    you can use <?= jap('したくありません', 'not want to do (polite)'); ?>, which is even more polite.
</p>
<p>
    Examples:<br>
    <?= jap('マダガスカル', 'Madagascar'); ?>
    <?= jap('に', 'existence particle'); ?>
    <?= jap('パンダ', 'black-white bamboo eating bear'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('いない', 'to not exist'); ?>
    ➤ There aren't Pandas in Madagascar.<br>
    <?= jap('ない', 'to not exist'); ?> would be wrong since Pandas are conscious living things.
</p>
<p>
    <?= jap('ぼく', 'I (youthful)'); ?>
    <?= jap('の', 'possession particle'); ?>
    <?= jap('にわ', 'garden'); ?>
    <?= jap('に', 'existence particle'); ?>
    <?= jap('はな', 'flower'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('たくさん', 'many'); ?>
    <?= jap('あります', 'to exist (polite)'); ?>
    ➤ There are so many flowers in my garden.<br> Also: I have many flowers in my garden.<br>
</p>
<p>
    <?= jap('いま', 'now'); ?>
    <?= jap('は', 'topic particle', true); ?>
    <?= jap('がっこう', 'school'); ?>
    <?= jap('に', 'existence particle'); ?>
    <?= jap('います', 'to exist'); ?>
    ➤ I'm at school now.<br>
</p>