<?=lessonHeader('Noun ' . roma('suru'));?>
<p>
    I apologise for the length of the last lessons. They weren't short as I wanted them to be - but they could be much
    longer. This lesson will be shorter, I swear.
</p>
<p>
    Some verbs are made by adding <?= jap('する', 'to do, to make'); ?> to nouns. For example,
    <?= jap('理解', 'understanding'); ?> plus <?= jap('する', 'to do, to make'); ?> becomes
    <?= jap('理解 する', 'to understand'); ?>. Often there're equivalents without a
    <roma>suru</roma>-construction, i.e. <?= jap('解る', 'to understand'); ?>. Both mean the same and also
    share the same Kanji <?= jap('解'); ?>. However, the <roma>suru</roma>-construction is more complicated and
    therefore more formal.
</p>
<p>
    There are many suru-nouns and new are discovered/created at the very moment. Unfortunately, it doesn't mean you can
    attach <?= jap('する', 'to do, to make'); ?> to every single noun. However, if a noun implies an
    action, it's very likely that a <roma>suru</roma>-construction already exists. For example, <?= jap('キス する', 'to kiss'); ?>
    is one of the new ones. The conjugation of suru-nouns applies to <?= jap('する', 'to do, to make'); ?> itself, of course.
</p>
<p>
    <?= jap('敗北', 'defeat'); ?>
    <?= jap('しません でした', 'to do (polite, negative, past)'); ?>
    ➤ They didn't lose.
</p>