<?= $global->lessonHeader('Irregularity'); ?>
<p>
    The structure of a language is never planned but develops of its own.
    Grammar wasn't <strong>created</strong>, but it was <strong>found</strong> by researchers a long time after its
    development. A language that is created shouldn't have any irregularities.
</p>
<p>
    Because of Japanese grammatical structure, there is hardly ever something irregular.
    And that's the easy thing about it, you can use formulas, that is always true.
</p>
<p>
    There are enough cases in that you can find an <strong>exception</strong> to the rule, but it's actually no
    exception because there <strong>isn't such rule</strong> that confirms it.
</p>
<?= $global->lessonNavigation(); ?>