<?= lessonHeader('Verbs'); ?>
<p>
    The job of linguists (language scientists) is to explain language and its rules.
    As Japanese verbs were explored, they found similarities and tried to group them by habits.
    In several learning books you can find different explanations. All of them have their advantages and disadvantages.
</p>
<p>
    Here's a suggestion (which will be used throughout the lessons):<br>
    All verbs <strong>end</strong> with a mora from the <strong>u-column</strong>.<br>
    Percisely:
    <roma>u</roma>
    ,
    <roma>ku</roma>
    ,
    <roma>gu</roma>
    ,
    <roma>su</roma>
    ,
    <roma>tsu</roma>
    ,
    <roma>nu</roma>
    ,
    <roma>mu</roma>
    ,
    <roma>bu</roma>
    , and
    <roma>ru</roma>
    .
</p>
<p>
    "So a verb simply ends with u?"<br>
    Can't deny this statement, but there are reasons that let me insist on the formulation above. One of the reasons is
    that if you take <strong>u</strong> as a letter it would be right, but it would be wrong if you assume it is a mora
    (see <a href="/Lessons/3">Lesson 3</a>). Other reasons will follow shortly.
</p>
