<?= lessonHeader('Verb Groups'); ?>
<p>
    Imagine a swimming pool full of m&m's or skittles. Some are bigger, some are rounder and some are inedible.
    You can sort them by shape, weight, or taste, but the easiest way is to sort them by colour. If you replace
    these
    little sweets with verbs and find other attributes for them, the sorting process would be very similar.
</p>
<p>
    In this suggestion, Japanese verbs are sorted by rules applied to them.
    The result of this sorting method resulted in four groups:
</p>
<ul>
    <li>
        <p>
            A group that contains just one verb:
            <?= jap('する', 'to do; to make'); ?><br>
            Rules applied to it are unique, so it's all alone in his group.
        </p>
    </li>
    <li>
        <p>
            A group just as little as the above one:
            <?= jap('くる', 'to come'); ?><br>
            It has its own unique rules, but in some explanations, both groups are put together.
        </p>
    </li>
    <li>
        <p>
            A group where rules are always applied to the stem. Let's call that group one-level-group or
            <strong>lvl1</strong>.<br>
            All lvl1-verbs have a mora from the <strong>i-column</strong> or <strong>e-column</strong> and
            <strong>ru</strong> at the end.<br>
            If you don't know what is meant by column or row, see this <a href="/Collection/HiraganaTable">
                <roma>hiragana</roma>
                table</a>.
            Depends on how the table is rotated, columns and rows could be swapped.<br>
            Examples:
            <?= jap('みる', 'to see; to watch'); ?>,
            <?= jap('はじめる', 'to begin; to start'); ?>,
            <?= jap('きる', 'to put on clothing'); ?>,
            <?= jap('ねる', 'to sleep'); ?>,
            <?= jap('たべる', 'to eat'); ?>
        </p>
    </li>
    <li>
        <p>
            A group where rules are applied depending on the ending. This group will be referenced as
            <strong>lvl5</strong>.<br>
            It contains all the verbs which can't be assigned to the other groups.<br>
            Examples:
            <?= jap('とぶ', 'to fly; to jump'); ?>,
            <?= jap('ころす', 'to kill; to murder'); ?>,
            <?= jap('つかう', 'to use'); ?>,
            <?= jap('まねく', 'to invite'); ?>,
            <?= jap('はしる', 'to run'); ?>
        </p>
    </li>
</ul>
<p>
    "The <?= roma('hashiru', 'to run'); ?> in the lvl5-example is actually lvl1, isn't it?"<br>
    Just like <?= jap('みる', 'to see; to watch'); ?>, <?= roma('hashiru', 'to run'); ?>
    has the same ending <strong>iru</strong>, but <?= roma('hashiru', 'to run'); ?> is lvl5 and
    <?= jap('みる', 'to see; to watch'); ?> is lvl1.
    You may think it's irregular because its form is lvl1, but then you have misunderstood something
    (see <a href="/Lessons/4">Lesson 4</a>).
    There isn't a rule that says that all verbs with iru or eru are lvl1.
    The rule says that all lvl1 have iru or eru at the end.<br>
    <strong>All thumbs are fingers, but not all fingers are thumbs!</strong>
</p>