<?= lessonHeader('Agglutination'); ?>
<p>
    Japanese in an agglutinative language, that means word construction is made by <strong>glueing</strong> words
    together to create a new word. Either grammatical elements or other words that function like these can also be
    attached to the word. The main advantage of agglutinative languages is, that irregularities are very rare.
</p>
<p>
    An Example to show agglutination (please ignore the grammar for now):
</p>

<table>
    <tr>
        <th>Stem</th>
        <th>Ending</th>
        <th>Transformation</th>
        <th>Attachment</th>
        <th>Result</th>
        <th>Meaning</th>
    </tr>
    <tr>
        <td><roma>yo</roma></td>
        <td><roma>mu</roma></td>
        <td></td>
        <td></td>
        <td><roma>yomu</roma></td>
        <td>to read</td>
    </tr>
    <tr>
        <td><roma>yo</roma></td>
        <td><roma>mu</roma></td>
        <td><roma><strong>mi</strong></roma></td>
        <td><roma>tai</roma></td>
        <td><roma>yomitai</roma></td>
        <td>want to read</td>
    </tr>
    <tr>
        <td><roma>yomita</roma></td>
        <td><roma>i</roma></td>
        <td><roma><strong>ku</strong></roma></td>
        <td><roma>nai</roma></td>
        <td><roma>yomitakunai</roma></td>
        <td>do not want to read</td>
    </tr>
    <tr>
        <td><roma>yomitakuna</roma></td>
        <td><roma>i</roma></td>
        <td><roma><strong>katta</strong></roma></td>
        <td></td>
        <td><roma>yomitakunakatta</roma></td>
        <td>did not want to read</td>
    </tr>
</table>

<p>
    Note how the <strong>ending changes</strong> before attaching to the next element. You can't just stick things
    together, with glue you can, hence <strong>plugging</strong> would be a better term for that. If you want to connect
    your XBOX to your TV, but it doesn't support HDMI, you cannot plug it in - but you can use an adapter. The ending
    functions as an adapter to connect two elements in <strong>different forms</strong>. There are 7 forms in total, the
    first one will be introduced in the next lesson. Agglutination will be discussed in
    <a href="/Lessons/14">Lesson 14</a> in more detail, so don't worry if don't get how it works right now.
</p>

