<?= lessonHeader('Verbs SSK'); ?>
<p>
    There's not much to add to the explanation from <a href="/Lessons/5">Lesson 5</a>, we already covered
    almost anything. You should remember the following separation because it will be important for other word forms.
</p>
<p>
    A verb contains a stem and an ending. The ending is the last mora of the verb. Anything until that is the stem.
    Get a look on <?= jap('わすれる', 'to forget'); ?>. The stem is
    <?= jap('わすれ'); ?> and the ending is <?= jap('る'); ?>.
    Remember, that the stem <strong>never</strong> changes.
</p>
<p>
    A verb in the SSK always ends with a mora from the u-column. Hence, every verb you've seen so far was was in its
    SSK. Easy, right?
</p>

