<h1>Section Futatsu</h1>
<p>
    text
</p>
<table class="grid-table">
    <tr>
        <td><a href="/Lessons/21">x</a></td>
        <td><a href="/Lessons/22">x</a></td>
        <td><a href="/Lessons/23">x</a></td>
        <td><a href="/Lessons/24">x</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/25">x</a></td>
        <td><a href="/Lessons/26">x</a></td>
        <td><a href="/Lessons/27">x</a></td>
        <td><a href="/Lessons/28">x</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/29">x</a></td>
        <td><a href="/Lessons/30">x</a></td>
        <td><a href="/Lessons/31">x</a></td>
        <td><a href="/Lessons/32">x</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/33">x</a></td>
        <td><a href="/Lessons/34">x</a></td>
        <td><a href="/Lessons/35">x</a></td>
        <td><a href="/Lessons/36">x</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/37">x</a></td>
        <td><a href="/Lessons/38">x</a></td>
        <td><a href="/Lessons/39">x</a></td>
        <td><a href="/Lessons/40">x</a></td>
    </tr>
</table>