<h1>Section Futatsu</h1>
<p>
    No text yet...
</p>
<div class="button-group">
    <a class="button" href="/Lessons/21">Start</a>
</div>
<ol class="lesson-list" start="21">
    <li><a href="/Lessons/21">Adjectives</a></li>
    <li><a href="/Lessons/22">Adjectives polite</a></li>
    <li><a href="/Lessons/23"><?= roma('Mizenkei'); ?></a></li>
    <li><a href="/Lessons/24"><?= roma('nai'); ?>-form</a></li>
    <li><a href="/Lessons/25">Topic Marking Particle</a></li>
    <li><a href="/Lessons/26">Direction Marking Particle</a></li>
    <li><a href="/Lessons/27">Movement</a></li>
    <li><a href="/Lessons/28">Question Particle</a></li>
    <li><a href="/Lessons/29"><?= roma('tai'); ?>-form</a></li>
    <li><a href="/Lessons/30">Scene Marking Particle</a></li>
    <li><a href="/Lessons/31">Locating</a></li>
    <li><a href="/Lessons/32"><?= roma('Rentaikei'); ?></a></li>
<!--    <li><a href="/Lessons/32">Noun Combining Particles</a></li>-->
    <!--    <li><a href="/Lessons/31">Aru & Nai & Masu</a></li>-->
    <!--    <li><a href="/Lessons/32">Particle Conflict Behaviour</a></li>-->
    <!--    <li><a href="/Lessons/33">Noun Combining Particle</a></li>-->
    <!--    <li><a href="/Lessons/34">--><? //= roma('te'); ?><!---form</a></li>-->
    <!--    <li><a href="/Lessons/35">Polite Request</a></li>-->
    <!--    <li><a href="/Lessons/36">Simple Potential Form</a></li>-->
    <!--    <li><a href="/Lessons/37">Giving Reason</a></li>-->
    <!--    <li><a href="/Lessons/38"></a></li>-->
    <!--    <li><a href="/Lessons/39"></a></li>-->
    <!--    <li><a href="/Lessons/40">Big Test Futatsu</a></li>-->
</ol>