<h1>Section Futatsu</h1>
<p>
    No text yet...
</p>
<div class="button-group">
    <a class="button" href="/Lessons/21">Start</a>
</div>
<ol class="lesson-list" start="21">
    <li><a href="/Lessons/21">Adjectives</a></li>
    <li><a href="/Lessons/22">Adjectives polite</a></li>
    <li><a href="/Lessons/23"><?= roma('Mizenkei'); ?></a></li>
    <li><a href="/Lessons/24"><?= roma('nai'); ?>-form</a></li>
    <li><a href="/Lessons/25">Theme Marking Particle</a></li>
</ol>