<h1>Section Hitotsu</h1>
<p>
    In this section, you'll learn how to give words functions by using particles. You'll also learn about two main word
    forms and how to append the <?= roma('masu'); ?>-form.
    Expand your knowledge with functional themes that help you
    understand Japanese and languages in general.
    <!--    In every lesson it is recommended to test yourself - knowledge without practice is worthless. -->
    The last lesson is a test containing the entire section, repeat it if you don't get
    the hang of it. In the end, you'll be able to determine objects, subjects, word forms and get a pro in the matter of
    verbs.
</p>
<table class="grid-table">
    <tr>
        <td><a href="/Lessons/1">Particles</a></td>
        <td><a href="/Lessons/2">Particle <?= roma('no'); ?></a></td>
        <td><a href="/Lessons/3">Spelling</a></td>
        <td><a href="/Lessons/4">Irregularity</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/5">Verbs</a></td>
        <td><a href="/Lessons/6">Verb Groups</a></td>
        <td><a href="/Lessons/7">Agglutination</a></td>
        <td><a href="/Lessons/8"><?= roma('Shūshikei'); ?></a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/9">Verbs SSK</a></td>
        <td><a href="/Lessons/10">Particle <?= roma('o'); ?></a></td>
        <td><a href="/Lessons/11">Sentence Construction</a></td>
        <td><a href="/Lessons/12">Tenses</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/13">Translation</a></td>
        <td><a href="/Lessons/14">Verb Agglutination</a></td>
        <td><a href="/Lessons/15"><?= roma('Ren\'yōkei'); ?></a></td>
        <td><a href="/Lessons/16"><?= roma('masu'); ?>-form</a></td>
    </tr>
    <tr>
        <td><a href="/Lessons/17">Particle <?= roma('ga'); ?></a></td>
        <td><a href="/Lessons/18">Copula</a></td>
        <td><a href="/Lessons/19">Masu & Copula</a></td>
        <td><a href="/Lessons/20">Big Test Hitotsu</a></td>
    </tr>
</table>