<h1>Section Hitotsu</h1>
<p>
    In this section, you'll learn how to give words functions by using particles. You'll also learn about two main word
    forms and how to append the <?= roma('masu'); ?>-form.
    Expand your knowledge with functional topics that help you
    understand Japanese and languages in general.
    <!--    In every lesson it is recommended to test yourself - knowledge without practice is worthless. -->
    The last lesson is a test containing the entire section, repeat it if you don't get
    the hang of it. In the end, you'll be able to determine objects, subjects, word forms and get a pro in the matter of
    verbs.
</p>
<p>
    <span class="main shuushikei">shuushikei</span>
    <span class="main ren'youkei">ren'youkei</span>
    <span class="main mizenkei">mizenkei</span>
    <span class="main rentaikei">rentaikei</span>
    <span class="main izenkei">izenkei</span>
    <span class="main suiryoukei">suiryoukei</span>
    <span class="main meireikei">meireikei</span>
</p>
<p>
    <span class="jap noun" content="I">わたし</span>
    <span class="jap particle topic-particle">は</span>
    <span class="jap na-adjective" content="important">たいせつ</span>
    <span class="jap copula-rentai">な</span>
    <span class="jap noun" content="thing">もの</span>
    <span class="jap particle subject-particle">が</span>
    <span class="jap verb masu-form" content="to exist">あります</span>
</p>
<div class="button-group">
    <a class="button" href="/Lessons/1">Start</a>
</div>
<ol class="lesson-list">
    <li><a href="/Lessons/1">Particles</a></li>
    <li><a href="/Lessons/2">Possession Particle</a></li>
    <li><a href="/Lessons/3">Spelling</a></li>
    <li><a href="/Lessons/4">Irregularity</a></li>
    <li><a href="/Lessons/5">Verbs</a></li>
    <li><a href="/Lessons/6">Verb Groups</a></li>
    <li><a href="/Lessons/7">Agglutination</a></li>
    <li><a href="/Lessons/8"><?= roma('Shūshikei'); ?></a></li>
    <li><a href="/Lessons/9">Verbs SSK</a></li>
    <li><a href="/Lessons/10">Object Marking Particle</a></li>
    <li><a href="/Lessons/11">Sentence Construction</a></li>
    <li><a href="/Lessons/12">Tenses</a></li>
    <li><a href="/Lessons/13">Translation</a></li>
    <li><a href="/Lessons/14">Verb Agglutination</a></li>
    <li><a href="/Lessons/15"><?= roma('Ren\'yōkei'); ?></a></li>
    <li><a href="/Lessons/16"><?= roma('masu'); ?>-form</a></li>
    <li><a href="/Lessons/17">Subject Marking Particle</a></li>
    <li><a href="/Lessons/18">Copula</a></li>
    <li><a href="/Lessons/19">Masu & Copula</a></li>
    <li><a href="/Lessons/20">Big Test Hitotsu</a></li>
</ol>