<h1>This page will be available soon...</h1>
<!--<h1>Lessons</h1>-->
<!--<p>-->
<!--    Prepare yourself You don't need to have previous experience, but you have to understand the essence of a lesson-->
<!--    before you move-->
<!--    on. I guarantee for high-quality-->
<!--    explanations combined with enjoyment.-->
<!--</p>-->
<!--<p>-->
<!--    There are some things you should know before you get started:<br>-->
<!--    Japanese words are written <em>cursive</em> to differentiate them from English, hence you should be aware of-->
<!--    "made" and "<em>made-->
<!--        <meaning>until; till; to</meaning>-->
<!--    </em>". As this page also provides a-->
<!--    <a href="hiragana-training.php"><em>Hiragana-->
<!--            <meaning>a Japanese writing system</meaning>-->
<!--        </em>-trainer</a>,-->
<!--    you have the chance to learn it simultaneously - Japanese words will be written in-->
<!--    <em>Kana-->
<!--        <meaning>the Japanese writing systems Hiragana and Katakana</meaning>-->
<!--    </em>.-->
<!--    If you can't read it, just click on it and it will turn in readable letters.-->
<!--    You can move your mouse over almost every cursive/Japanese word to get its meaning.-->
<!--    <br>Move your mouse over it and then click it:-->
<!--    <jap>いぬ-->
<!--        <meaning>dog</meaning>-->
<!--    </jap>-->
<!--    <jap>と-->
<!--        <meaning>combining particle (and; with)</meaning>-->
<!--    </jap>-->
<!--    <jap>ねこ-->
<!--        <meaning>cat</meaning>-->
<!--    </jap>-->
<!--    .-->
<!--</p>-->
<!--<p>-->
<!--    This page is still in progress, so try to keep up. If you have suggestions for improvement or find a mistake or-->
<!--    just want to criticise my terrible English, please contact me.-->
<!--</p>-->
<div class="button-group">
    <a class="button" href="/Lessons/Hitotsu">Start Lessons</a>
</div>
