<div class="navigation">
    <ul class="navigation-menu">
        <li>
            <div class="menu">
                <a href="#"><h6>Home</h6></a>
                <ul class="menu-dropdown">
                    <li><a href="/Introduction">Introduction</a></li>
                    <li><a href="/HowToUse">How To Use</a></li>
                    <li><a href="Donate">Dontate</a></li>
                </ul>
            </div>
        </li>
        <li>
            <div class="menu">
                <a href="#"><h6>Lessons</h6></a>
                <ul class="menu-dropdown">
                    <li><a href="/Lesson/Start">Start</a></li>
                    <li><a href="/Lesson/Hitotsu">Hitotsu</a></li>
                    <li><a href="/Lesson/Futatsu">Futastu</a></li>
                </ul>
            </div>
        </li>
        <li>
            <div class="menu">
                <a href="#"><h6>Training</h6></a>
                <ul class="menu-dropdown">
                    <li><a href="/Training/Hiragana">Hiragana</a></li>
                    <li><a href="/Training/Katakana">Katakana</a></li>
                    <li><a href="/Training/VerbForms">Verb Forms</a></li>
                    <li><a href="/Training/KanjiReading">Kanji Reading</a></li>
                </ul>
            </div>
        </li>
        <li>
            <div class="menu">
                <a href="#"><h6>Collection</h6></a>
                <ul class="menu-dropdown">
                    <li><a href="/Collection/Hiragana">Hiragana</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>