<script src="<?= '/Assets/JS/kanji_process.js'; ?>"></script>
<script src="<?= '/Assets/JS/Kanji.class.js'; ?>"></script>

<h1>Kanji Training</h1>

<p>
    Use this training program to improve your Kanji reading skills. Get a look on the
    <a href="/Collection/KanjiList">
        <?= roma('kanji', 'chinese characters'); ?> list
    </a> if you want to learn them before training. Although the training alone is recommended.
</p>
<p>
    <?= roma('Kanji', 'chinese characters'); ?> are very hard at the beginning but get easy pretty fast.
</p>

<div class="training">
    <div class="prepare">
            <button id="group1" class="start-button">
                <div class="header">Group 1</div>
                <div class="description">20 random test words</div>
                <div class="demo">
                    <jap>忍　飛　生　行　時</jap>
                </div>
            </button>
            <button id="group2" class="start-button">
                <div class="header">Group 2</div>
                <div class="description">20 basic shit</div>
                <div class="demo">
                    <jap>風　国　姉　鳥　雷</jap>
                </div>
            </button>
            <button id="group3" class="start-button">
                <div class="header">Group 3</div>
                <div class="description">20 hard ones</div>
                <div class="demo">
                    <jap>獄　態　滅　違　僧</jap>
                </div>
            </button>
    </div>
    <div class="start">
        <div class="info"></div>
        <div class="task"></div>
        <div class="input">
            <input type="text" class="result" placeholder="Reading">
            <button class="skip">I have no idea</button>
        </div>
        <div class="progress"></div>
    </div>
    <div class="end">
        <h3>Rank reached:</h3>
        <p class="rank"></p>
        <p class="advice"></p>
        <div class="button-group">
            <a class="start-over button">Start Over</a>
        </div>
    </div>
</div>