<h1>Another Japanese Learning Website</h1>

<h2>Welcome buddy</h2>
<p>
    Interested in the japanese language? Finding a course isn't that easy for many people. Japanese speakers aren't
    everywhere, in addition yet, some people just haven't the time or funds for visiting classes. Textbooks lack of
    explanations and personal support. That's why I created this website, so everyone can access it and get his/her
    questions answered.
</p>

<h2>Expectations</h2>
<p>
    My goal isn't about preparing you for business life in a big company in
    <?= roma('Tōkyō', 'capital of Japan'); ?>, nor do I want you to
    learn stuff you'll never need. I don't know what motivates you or what your goals are, but if you agree that
    <strong>subtitles suck</strong>, then here's the right place to keep up. Indeed, this site is
    <?= roma('otaku', 'HERE: fans of japanese popular culture'); ?>-oriented, but I'll
    do my best to provide high-quality but easy-to-understand lessons while focusing on the main goal.
</p>

<h2>Click them all!</h2>
<p>
    <?= jap('日本語', 'japanese'); ?>
    <?= jap('を', 'object particle', true); ?>
    <?= jap('勉強', 'learning'); ?>
    <?= jap('したい', 'want to do'); ?>
    <?= jap('です。', 'HERE: politeness marker'); ?>
</p>
<p>
    Isn't that nice? You can do this throughout the site. Notice that japanese words are written italic. That's not only
    for drawing your attention, but to force <strong>japanese pronunciation</strong>.
</p>
<p>
    You may find this functionality
    confusing or unnecessary, but it's actually a great option. By moving your mouse over a particular word you get a
    meaning of it that is best suited in that particular case, otherwise you will have a very hard time with
    dictionaries. Learning <?= roma('Kanji', 'japanese writing system, which originated in china'); ?> and
    <?= roma('Kana', 'japanese basic writing systems Hiragana and Katakana'); ?> is not a requirement but a
    possibility - because you can click it away. Actually, I know nobody who is interested in this language but
    rejecting its writing system.
</p>
<p>
    By the way, the meaning of the sentence above is "I want to learn japanese.", if you don't figured it out yet. Let
    us explore the lessons to understand how it works.
</p>

<h2>Lessons</h2>
<p>
    They are structured in bite-sized pieces covering single issues respectively. Every 20 lessons are packed into
    sections with a test as the last lesson. Some lessons teaching about languages in general. Please don't skip them,
    provided that you aren't a linguist. It's recommended to find a proverb for yourself, that describes a lesson best.
    You can access the Lessons <a href="/Lessons/">here</a>.
</p>

<h2>Trainer</h2>
<p>
    This site also offers training programs that help you learn
    <?= roma('Hiragana', 'one of the japanese writing systems'); ?>,
    <?= roma('Katakana', 'another japanese writing system'); ?> and
    <?= roma('Kanji', 'japanese writing system, which originated in china'); ?> reading. Many other
    trainers are planned. Trainers can be found <a href="/Training/">here</a>.
</p>

<h2>Non-profit</h2>
<p>
    This site is <strong>completely free</strong>.  However, if you feel the desire to help this site running, I would
    be very thankful for a coin.
</p>

<h2>Recruiting</h2>
<p>
    As you probably noticed, my english skills aren't that well. I have to admit that I need some support here. If you
    have a bit of time to offer, you are welcome to "join the club".
</p>

<h2>In progress</h2>
<p>
    This site is still in development. Many functions and services are planned. New lessons will be uploaded asap,
    depending on my free time. I also would appreciate your feedback, suggestions for improvement or just bug reports.
</p>