<h1>Japanisch lernen mit Nipponjaku</h1>

<h2>Āā Ēē Īī Ōō Ūū</h2>
<p>
    <?= jap('日本語', 'japanese'); ?>
    <?= jap('を', 'object particle', true); ?>
    <?= jap('勉強', 'learning'); ?>
    <?= jap('したい', 'want to do'); ?>
    <?= jap('です。', 'copula; here: politeness marker'); ?>
    <br>
    <?= jap('私', 'I'); ?>
    <?= jap('は', 'theme particle', true); ?>
    <?= jap('マンハイム', 'Mannheim, a city in Germany'); ?>
    <?= jap('に', 'direction particle'); ?>
    <?= jap('行きたい', 'want to go'); ?>
    <?= jap('けど、', 'but; however'); ?>
    <?= jap('時間', 'time'); ?>
    <?= jap('が', 'subject particle'); ?>
    <?= jap('ありません。', 'aren\'t; haven\'t'); ?>
</p>

<h3>Math Operations</h3>
<p>
    You can do basic math operations to numerical values and colors. Lets say we want to have two divs placed next to
    each other, the second one being twice as wide and with a different background. LESS knows what the measuring units
    are and won't mess them up. You can do basic math operations to numerical values and colors. Lets say we want to
    have two divs placed next to each other, the second one being twice as wide and with a different background. LESS
    knows what the measuring units are and won't mess them up.
</p>